spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: fic-auth_oauth
          uri: lb://fic-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        - id: fic-user
          uri: lb://fic-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: fic-kanban
          uri: lb://fic-kanban
          predicates:
            - Path=/api/kanban/**
          filters:
            - StripPrefix=1
        - id: fic-kanban_invitation
          uri: lb://fic-kanban
          predicates:
            - Path=/api/invitation/**
          filters:
            - StripPrefix=1
        - id: fic-search
          uri: lb://fic-search
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
        - id: fic-mail
          uri: lb://fic-mail
          predicates:
            - Path=/api/mail/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:4011/rsa/publicKey'
  redis:
    database: 0
    port: 6379
    host: localhost
    password: redis123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/api/oauth/**"
      - "/api/user/register"
      - "/api/mail/verification-code/**"
      - "/api/user/password/reset" 